package com.revenat.ishop.infrastructure.framework.annotation.persistence.repository;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.sql.ResultSet;

import com.revenat.ishop.infrastructure.framework.handler.ResultSetHandler;
import com.revenat.ishop.infrastructure.framework.handler.base.DefaultResultSetHandler;

/**
 * This annotation is used to annotate repository interface method that should
 * use SQL Insert query to persist entity into underlaying relational database.
 * Can be placed on method with single argument only, either entity instance or
 * collection of entity instances to be inserted.
 * 
 * @author Vitaly Dragun
 *
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Insert {
	/**
	 * Should be set to {@code true} if such annotation placed on method which takes
	 * collection of entities as argument. If annotated method takes only single
	 * entity instance, should be left as default {@code false} state.
	 */
	boolean batchInsert() default false;

	/**
	 * {@link ResultSetHandler} implementations for handling {@link ResultSet}
	 * generated by executing SQL query and transforming it into appropriate type.
	 */
	@SuppressWarnings("rawtypes")
	Class<? extends ResultSetHandler> resultSetHandlerClass() default DefaultResultSetHandler.class;
}
